### ISSUE TITLE
anki addon updated without new commits?

### ISSUE THREAD

**Issue by voidplayer** [sobjornstad/AnkiLPCG#33]
This addon has been updated today in anki without new commits. Are you using a different repo or have you been hacked?

**Comment by sobjornstad** [comment]
No, I didn't update LPCG. This looks like a bug in Anki to me, because the AnkiWeb page still shows the last updated date in 2021.

![image](https://user-images.githubusercontent.com/2313414/169060745-191a3df7-8644-4a47-ae3f-f0e2c8742830.png)

**Comment by sobjornstad** [comment]
I had it installed symlinked to the development version on my PC, rather than through AnkiWeb. I'm going to download it right now and diff it against my local build just to be safe.

**Comment by voidplayer** [comment]
I diffed it against master and theres a new dialog window, although is hard to tell if it did something else, since i run it before doing the diff

**Comment by sobjornstad** [comment]
There's no difference for me. What version of Anki are you using? Possible you got a different one due to that?

(I also discovered I have some local changes I forgot to publish, but that's a different issue)

**Comment by voidplayer** [comment]
I was in 1.49 when it happened. I just updated to 1.52

**Comment by sobjornstad** [comment]
OK, here are the facts:

* AnkiWeb's date stamp aligns with the datestamp on `master` in the repository (July 24, 2021). I have not updated either the public repository or AnkiWeb this year at all, much less in the last couple of days.
* The version on my *local* repository (which has 2 commits not on public `master`, not sure how that happened) was last updated January 6, 2022. I guess I meant to publish a new version then.
* You're seeing an "addition" of `import_dialog.py` in your diff because that's generated code, and as such is included in the build, but not in the repository. If you run `make` in your repository (and you have all the right devtools), that difference should go away.
* When I clean and rebuild locally from `origin/master` and diff an extract of the resulting `.ankiaddon` file against the version in the plugin I just downloaded, everything is identical (except the `meta.json` and the `__pycache__`, which are created by Anki as it uses the plugin).

So I think everything is fine and as expected (except that I need to cut a new version because I forgot to).

However, I still have no idea at all why you were informed there was an update even though no update has been published to AnkiWeb, unless you had an older version for a long time and Anki only noticed the version published a year ago (!) recently for some reason? Out of an abundance of caution, I have changed my AnkiWeb password, but if you're concerned you should probably report this to the main Anki repository, as there's not really any reason to think that if there was some kind of security issue, it was on my side. I don't think there's any reason to be concerned since the code is identical though.

**Comment by voidplayer** [comment]
Okay, i check the date in my files, and i was in `1.43` 2 days ago, so that is the problem. Most addons have updated now

Im kinda embarrassed for entering panic mode 😅

Thanks for the troubleshooting! And the addon!
