### ISSUE TITLE
Issue of switching between texts often during reviews

### ISSUE THREAD

**Issue by voidray** [sobjornstad/AnkiLPCG#8]
I really like the addon and use it to memorize texts. One thing I don't like so much (that is inherent by the way it anki and the addon works) is that during review I constantly have to switch between the different texts. This can get in the way when trying to memorize many different texts (especially if you you have texts with similar but still different passages).
Any thoughts on that issue? 
One workaround could maybe be to set a tag for each Text (poem,...) and then create custom study decks for each tag. If I select the parent deck for studying then the sub decks (custom study decks) would get reviewed once at a time if I recall correctly. I already have a lot of decks already however and the texts get more and more...

**Comment by sobjornstad** [comment]
I'm not really aware of a solution in the current version of Anki I'm afraid, either on your end or on LPCG's end. :(

Personally, I like the randomization as I find it helps me to make connections between different texts when they end up juxtaposed in unexpected ways, but I can see not appreciating it so much, especially if your collection of texts is fairly new or your texts are very long and you're doing a lot of reviews of the same text on any given day.

If you were going to go with the method of using separate decks, it might be easier to use actual decks instead of custom study decks so you wouldn't have to deal with rebuilding them all, but I can't think of any really strong reason to recommend either method. Either would work, but might end up making Anki run considerably more slowly since all the decks have to be scanned on many operations, and of course it would also be annoying to unnecessarily have dozens of decks.

**Comment by sobjornstad** [comment]
Closing as I don't think there's anything I can do about this the way Anki is currently designed. Feel free to reopen if you have specific suggestions for things I could change.
